version: "3"
services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/Dockerfile
    environment:
      HOST: 0.0.0.0
    ports:
      - 8081:80
    volumes:
      - ./:/code
